# Generated by Django 5.1 on 2024-11-18 16:39

from django.db import migrations

def cargar_datos_iniciales(apps, schema_editor):

    Juego = apps.get_model('EvaApp', 'juego')


    datos_iniciales = [
        {"nombre": "The Legend of Zelda: A Link to the Past", "consola": "SNES", "precio": 6500, "imagen": "zelda_alttp.jpg", "cantidad": 8, "estado": "Disponible"},
        {"nombre": "Super Mario Bros. 3", "consola": "NES", "precio": 5000, "imagen": "super_mario_bros3.jpg", "cantidad": 10, "estado": "Disponible"},
        {"nombre": "Sonic the Hedgehog 2", "consola": "SEGA", "precio": 4000, "imagen": "sonic2.jpg", "cantidad": 7, "estado": "Disponible"},
        {"nombre": "Donkey Kong Country", "consola": "SNES", "precio": 6000, "imagen": "dk_country.jpg", "cantidad": 9, "estado": "Disponible"},
        {"nombre": "GoldenEye 007", "consola": "N64", "precio": 5500, "imagen": "goldeneye007.jpg", "cantidad": 6, "estado": "Disponible"},
        {"nombre": "Crash Bandicoot: Warped", "consola": "PS1", "precio": 5000, "imagen": "crash_warped.jpg", "cantidad": 5, "estado": "Disponible"},
        {"nombre": "Resident Evil: Code Veronica", "consola": "Dreamcast", "precio": 7000, "imagen": "re_code_veronica.jpg", "cantidad": 4, "estado": "Disponible"},
        {"nombre": "Final Fantasy VII", "consola": "PS1", "precio": 6800, "imagen": "ff7.jpg", "cantidad": 6, "estado": "Disponible"},
        {"nombre": "Metroid Prime", "consola": "N64", "precio": 6200, "imagen": "metroid_prime.jpg", "cantidad": 8, "estado": "Disponible"},
        {"nombre": "Street Fighter II Turbo", "consola": "SNES", "precio": 5300, "imagen": "sf2_turbo.jpg", "cantidad": 7, "estado": "Disponible"},
        {"nombre": "The Legend of Zelda: Ocarina of Time", "consola": "N64", "precio": 7000, "imagen": "zelda_oot.jpg", "cantidad": 9, "estado": "Disponible"},
        {"nombre": "Tetris", "consola": "NES", "precio": 3000, "imagen": "tetris.jpg", "cantidad": 12, "estado": "Disponible"},
        {"nombre": "Sonic Adventure", "consola": "Dreamcast", "precio": 6000, "imagen": "sonic_adventure.jpg", "cantidad": 5, "estado": "Disponible"},
        {"nombre": "Pokémon Stadium", "consola": "N64", "precio": 5500, "imagen": "pokemon_stadium.jpg", "cantidad": 6, "estado": "Disponible"},
        {"nombre": "Mega Man X", "consola": "SNES", "precio": 4800, "imagen": "megaman_x.jpg", "cantidad": 7, "estado": "Disponible"},
        {"nombre": "Chrono Trigger", "consola": "SNES", "precio": 7500, "imagen": "chrono_trigger.jpg", "cantidad": 5, "estado": "Disponible"},
        {"nombre": "Shenmue", "consola": "Dreamcast", "precio": 8000, "imagen": "shenmue.jpg", "cantidad": 4, "estado": "Disponible"},
        {"nombre": "Castlevania: Symphony of the Night", "consola": "PS1", "precio": 6200, "imagen": "castlevania_sotn.jpg", "cantidad": 5, "estado": "Disponible"},
        {"nombre": "Mario Kart 64", "consola": "N64", "precio": 5000, "imagen": "mariokart64.jpg", "cantidad": 6, "estado": "Disponible"},
        {"nombre": "Sonic the Hedgehog 3 & Knuckles", "consola": "SEGA", "precio": 5500, "imagen": "sonic3_knuckles.jpg", "cantidad": 8, "estado": "Disponible"},
    ]

    # Crea los registros en la base de datos
    for datos in datos_iniciales:
        Juego.objects.create(**datos)

class Migration(migrations.Migration):
    dependencies = [
        ('EvaApp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(cargar_datos_iniciales),
    ]
